[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_tokens_program = "CSqtsYXnt2UfXttszwG6rGFFY7EedJ5kmn4xEyas4LeE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
