[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rent_example = "3efkmFTva1SZmFPt7E2nTe6SkCLUfuzayXgfjsMJr5Ac"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
