[project]
name = "quasar_token_2022_immutable_owner"

[toolchain]
type = "solana"

[testing]
language = "rust"

[testing.rust]
framework = "quasar-svm"

[testing.rust.test]
program = "cargo"
args = [
    "test",
    "tests::",
]

[clients]
path = "target/client"
languages = ["rust"]
