[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
immutable_owner = "FwsJpDYJ1UkYHq6rGYD7sXY1fStiBTfLpApazzj9khS7"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
