[package]
name = "token-2022-non-transferable-program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "1.5.7"
solana-program = "2.0"
spl-associated-token-account = { version="2.0.0", features = [ "no-entrypoint" ] }
spl-token-2022 = {version = "0.7.0", features = [ "no-entrypoint" ] }

[lib]
crate-type = ["cdylib", "lib"]
