[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_sol = "HU7QEokj5qUUV5ryZYL7EhsqiAkxJyMVXc3DesKyCqtF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
