[package]
name = "create-account-program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program.workspace = true
solana-system-interface.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
