[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook = "FEu8GvcwSvmeaf8hQ2SvfzSYcSNSuB32WdfYUARTcmqp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
