/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

export * from './blockWallet';
export * from './init';
export * from './setupExtraMetas';
export * from './unblockWallet';
