[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "7GWQBBQmcfjWdnyjkXdxUXeDxp2mW1WsGtMhpsFD8eKN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/apple/.config/solana/id.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
