[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "Gd65x65gsd55JTEbpbB7B5ukg8Q6hctXzyGcWiTmzxjK"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]

[test]
startup_wait = 25000
shutdown_wait = 2000
upgradeable = false
