[package]
name = "spl-token-minter-steel-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
steel.workspace = true
spl-token-minter-steel-api = {path = "../api"}

