//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#block_wallet;
pub(crate) mod r#init;
pub(crate) mod r#setup_extra_metas;
pub(crate) mod r#unblock_wallet;

pub use self::r#block_wallet::*;
pub use self::r#init::*;
pub use self::r#setup_extra_metas::*;
pub use self::r#unblock_wallet::*;
