[package]
name = "block-list"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]
name = "block_list"

[dependencies]
bytemuck = "1.23.0"
pinocchio = "0.8.4"
pinocchio-pubkey = "0.2.4"
pinocchio-system = "0.2.3"
pinocchio-log = "0.4.0"
