[package]
name = "cross-program-invocation-steel-hand"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
steel.workspace = true
cross-program-invocation-steel-hand-api = { path = "../api" }
