[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_solana = "52rNd2KDuqHaxs2vEFfEjH2zwKScA2B9AyW8F2fAcca8"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
