[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
close_account_program = "E7Cgyech7DrHz39ctmsPe6xqe65YJKWg1jwQQpmZrtcm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
