[package]
name = "close-account-steel-api"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program.workspace = true
steel.workspace = true
bytemuck.workspace = true
num_enum.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
