[package]
name = "processing-instructions-steel-program"
version = "0.1.0"
edition = "2021"

[dependencies]
steel.workspace = true
processing-instructions-steel-api = {path = "../api"}

[lib]
crate-type = ["cdylib", "lib"]
