[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.devnet]
fundraiser = "Eoiuq1dXvHxh6dLx3wh9gj8kSAUpga11krTrbfF5XYsC"

[programs.localnet]
fundraiser = "EuqudshRf8VRskatC6U3txgivHmtCkY5d1qsK5B3VAio"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
