[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
account_data_anchor_program = "77pvTicQMoPQXrf97tCtuzgPQuS69U5oYsU99LYdqyLF"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
