//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#config;
pub(crate) mod r#extra_metas;
pub(crate) mod r#wallet_block;

pub use self::r#config::*;
pub use self::r#extra_metas::*;
pub use self::r#wallet_block::*;
