[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
cpi_example = "A6reKAfewwif4GxzqpYTr1CLMKp2mwytKaQrjWdPCsBi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"