[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
create_system_account = "ALfCAvL1Vbm15QabQJ72NUi7LK7fB5YP2tDKEvvh7wS8"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
