[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mint_close_authority = "2wT6WQQqD4P35mDQJAWbWAMzFfCeLsYEELTde6jLQyKN"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
