[package]
name = "token-2022-multiple-extensions-program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh.workspace  = true
borsh-derive.workspace = true
solana-program.workspace = true
solana-system-interface.workspace = true
spl-token-2022-interface.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
