[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook = "Gkhsnn4Svph2FUNKbNHXQiKHpXWv6xfUBxitSxs7EzW2"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
