[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "4wHiZQvMXQKaF1BbgN9Y9D5g1dZersK3J7mLGG5cUjEm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
