[package]
name = "checking-accounts-steel-program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.18.17"
steel = "2.0"
bytemuck = "1.14"
num_enum = "0.7"

[lib]
crate-type = ["cdylib", "lib"]
